### ISSUE TITLE
Quick Ask - Optional tweak on 'visible in child groups'

### ISSUE THREAD

**Issue by HiveMindNet** [dcavins/hierarchical-groups-for-bp#13]
Hi David - Still enjoying the plugin thanks...

I have a child group showing content from a parent group - that all works great. However, I'd really like the parent content to show in the child group even if/when members of the child group are not members of the parent group. Currently the parent group content is only visible to members of both groups.

I'm happy to hack this to work myself if you could please point me in the right direction? If I manage I'll of course share back here in case you or anyone else needs the same.

Thank you.

**Comment by dcavins** [comment]
If both groups are public, it should work. Basically, the privacy settings
follow buddypress activity visibility. If you want to change the behavior,
look for the filter on bp_after_has_activities_parse_args.

David

**Comment by HiveMindNet** [comment]
Thanks David - they are both private I'm afraid, yes.

I took a look and sadly, I can't see how to do it. So I wanted to ask, is there any way you could possible look at it and I'll pay for the time, either on invoice or donation? I basically have 1 parent and 3 children that I'm focused on. I've set the parent activity to be visible in the 3 children, but not the other way around. All groups are private. I'd like members of just each child to see the activity from the parent with working links even if the viewer is only a member of the parent, (not the child). I expect this would upon clicking then take them to the page suggesting they request membership to the parent.

If you could help with this I'd very much appreciate it.

Thank you.

**Comment by HiveMindNet** [comment]
I should add that I'd be happy with a hard-coded fix for this. These 4 groups could be named in the code as this is not something I will need to work on any other groups so won't need a back/end GUI/admin area.

**Comment by HiveMindNet** [comment]
Hi @dcavins - any chance you could pass another comment on this if poss please?

Much appreciated :)
