### ISSUE TITLE
Remove Hierarchy From Group Creation Steps

### ISSUE THREAD

**Issue by robmcclel** [dcavins/hierarchical-groups-for-bp#14]
First, this plugin is amazing and goes a long way to solving an issue of mine.  Thank you tremendously for your efforts in creating it.

Is it possible to have the option (or perhaps apply a filter) to remove the assignment of the hierarchy during the group creation process?  For my particular application, it's a bit problematic to have it in that location, I would prefer to only have that as an option for the group admin after creation - or even only for the Network Admin via the BP Group dashboard.

Thanks,
Rob

**Comment by dcavins** [comment]
Hi @robmcclel-

I've just updated the plugin and included a new filter `hgbp_group_extension_screens_param`that will allow you to modify the screens parameter.

Thanks for the suggestion!

-David
