### ISSUE TITLE
Force parent group by default

### ISSUE THREAD

**Issue by Darkool** [dcavins/hierarchical-groups-for-bp#16]
Hi there, thank you so much for this plugin, I would like to know if is possible force a parent group(s) by default.

Then everytime time that I created a new group it will be a child of default parent(s)

Regards.

**Comment by dcavins** [comment]
I don't know how to do what you're asking, but it seems to me that you could use a hook in BuddyPress to set the parent for new groups in `groups_create_groups()`: https://github.com/buddypress/BuddyPress/blob/2.9.3/src/bp-groups/bp-groups-functions.php#L99

This is untested, but it might look something like this:

```
add_action( 'groups_create_group', function ( $group_id, $member, $group ){
	if ( 0 === $group->parent_id ) {
		$group->parent_id = $desired_parent_id;
		$group->save();
	}
}, 10, 3 );
```

BuddyPress is loaded with hooks, so you can pretty much find an action point to change its behavior.

Best,

-David
