### ISSUE TITLE
Replacing old BPGH plugin

### ISSUE THREAD

**Issue by kalico1** [dcavins/hierarchical-groups-for-bp#6]
Thanks for creating a replacement for BPGH. It's vital to the way we set up our site, but it's failing at too many points to be sustainable.

I have a couple questions before giving this new plugin a try. 

Does it have any compatibility with the hierarchy I've already created using BPGH? Or do I have to completely set up the entire hierarchy from the ground up?  Do I have to go through existing groups one by one and give them a parent, or is there some sort of interface where I can select multiple?

I have about 200 groups that are subgroups of a single parent -- so having some idea what i'm up against before I get started would be really helpful.

Thanks

**Comment by dcavins** [comment]
Hi @kalico1-

The newer plugin uses the same info source as the older plugin (BPGH added a `parent_id` column to the groups table; newer version of BP include that column, which I use in this plugin).

There's also an importer to move an important setting over from your BPGH installation. Once the new plugin is enabled, visit the settings screen: /wp-admin/admin.php?page=hierarchical-groups-for-bp
(it's under the "Groups" menu item, called "hierarchy options" ).

There is no bulk interface for making changes, although you could do it via your database. 

I think everyone who's using the new plugin is migrating from the old one, so I hope you won't have too much trouble. You can always go back to BPGH if you do--the data will still be intact.

-David

**Comment by kalico1** [comment]
Thanks, @dcavins for the quick reply. I've installed the plugin, deactivated BPGH, and I can see all the settings on the plugin page as well as on group pages. It is network activated.

But I'm getting an Access Denied message no matter what settings I try to save, or tools I run, from the settings page (I can save individual groups without issue. If you have any ideas from your vantage point, I'm all ears. Otherwise, I have some testing to do to figure out what's wrong.

For the record, I do have BP network activated, but I have added the root blog constant in wp-config, so it's not the main blog. Does that cause any issues with permissions?

**Comment by dcavins** [comment]
Ah. Well, that's awkward. I used the WP Settings API to set these items, but didn't know there were some issues with network setups. I'll have to update the admin section to work differently.

Thanks for your report!

**Comment by dcavins** [comment]
@kalico1 Can you test my changes in this branch? https://github.com/dcavins/hierarchical-groups-for-bp/tree/network-admin-form

I copied some of BP's logic to handle saving the values in a network or single-site environment. It's working on my networked installation, but there are at least 31 flavors. :)

Thanks!

**Comment by kalico1** [comment]
@dcavins Thanks - I got this running on my dev server and I'm quite pleased - with a couple of minor questions/issues.

I was able to set the first option " Show a hierarchical directory." and I ran the import script. All good there.

"Customize Label" isn't working, though. It doesn't affect the Hierarchy tab on the "Manage Group" page. (Am I looking in the right place? Seems like this is just a settings tab, not a place where one would need to list the # of subgroups on the tab......)

I like the new way that the child groups display. It's much cleaner than the (+) and (-). However, I would like to change the words "Child groups" or perhaps hide the child groups in some cases. I'm sure the latter could be done with CSS, and the former with language files (is this localized?), but it would be nice to have an option in admin, if you get around to it.

I haven't tested the two group activity settings, because this isn't something I want to mess with on my site at this point. I would like to understand the ramifications better first. But we're fine with how things have been, so I assume this will just default to "how it was".

Oh, I almost forgot to mention that group search is working now -- that was a huge problem we had with the last incarnation of BPGH/BP2.8 (which was patched to work in other ways, but broke search). 

Thank you for all the amazing work on this. I'm a happy camper and my staff will be happy to have everything updated and not hear me say "Soon...." again, lol

**Comment by dcavins** [comment]
Hi @kalico1. Thanks for your feedback.

"Customize label" affects the label of the "hierarchy" tab label in a group:
![hierarchy___group_986___bp_test](https://cloud.githubusercontent.com/assets/1391994/23491881/ae99c6e8-fec6-11e6-8813-c767d050db40.png)

Re language choices. There's been one other request to change that "child groups" label. It is translatable (see the readme file for details about where to put your translation files and what to name them), but it's also one of the very few persistent front-facing labels, so I guess adding an option isn't a bad idea.

Thanks for your feedback, and definitely try out the group activity syndication feature. It's one of the real pluses of nested groups, in my opinion. It doesn't affect how activity items are saved or stored, just how they're displayed, so there's not much risk in trying it out.

Best,

-David

**Comment by kalico1** [comment]
Thanks for the info and the suggestion. We are actually taking steps to prevent our users from posting to their activity feed, because we want them to focus their efforts in the forums. So for the particular site I'm working on now, it's not a feature we need, but I'm sure it will be great for other use cases. Thanks so much for your work on this important plugin.

**Comment by dcavins** [comment]
Hi @kalico1- 

I've added a couple of new settings that allow customization of important strings without adding a language file in https://github.com/dcavins/hierarchical-groups-for-bp/commit/96cd794f2c333cdea1efd2ca9683b89338ca7fc0.

I'm also getting ready to publish this plugin to the WordPress.org plugins repo. If you have any further comments now that you've been using this plugin for awhile, please let me know.

Thanks!

-David

**Comment by kalico1** [comment]
It's been a while, but I wanted to follow up. I finally implemented this on my live site today, because I started getting some permission errors that I traced back to BPGH. 

The process was very smooth. And I am very happy about the addition of custom labels!! Everything looks great; it even picked up all the right styling.

The only thing I added (other than the labels) is some CSS to remove the use tree view” toggle checkbox from the main page entirely. 

We have a lot of subgroups that are meaningless to most users, so we don't display them. I didn't want end users to have the option of toggling them on, and thereby detracting from the top-level groups that we are trying to highlight. 

This CSS did the trick:

```
li .hgbp-enable-tree-view-container .no-ajax {
  display: none;
}
```

Thanks again for making this awesome plugin to replace BPGH. It definitely fills a big gap! Hope to see it in the repo soon.

**Comment by dcavins** [comment]
Thanks very much for the feedback!

Yes, I'm planning to push this over to the WP plugins repo, but I've been swamped, and admit that I'm putting it off because I don't have time to deal with the (likely) support requests for the new plugin. :)

Thanks again for your thorough testing and feedback.

-David
