### ISSUE TITLE
Feature Request - Option to set/limit number of levels of hierarchical sub-groups

### ISSUE THREAD

**Issue by codename062** [dcavins/hierarchical-groups-for-bp#8]
I would like to limit the group admins to limit the number of hierarchical levels of sub-groups to one. I mean that a users should not be able to create a sub-group within a sub-group. User should be able o create a sub-group within a parent/root group.

**Comment by dcavins** [comment]
Hi @codename062-

You can add a filter that changes the "create_subgroups" capability. Here's how the base capability is calculated:
https://github.com/dcavins/hierarchical-groups-for-bp/blob/master/public/class-hgbp.php#L466

Here's an additional filter I wrote up as an example. I think it should do what you're asking (only allow one level of child groups--parents and children, no grandchildren).
https://gist.github.com/dcavins/e6891f1c9bbeab75fc1cfe38b33d9435

You can add it to your bp-custom.php file to try it out. Let me know how it works out for you. Thanks!

It wouldn't be any big deal to add it to the plugin as a setting, if I could figure out how to explain the levels. ;)

-David
